name: ${name}
version: ${version}
author: ${author}
main: ${mainClass}
commands:
  scare:
    description: Scare another player with a hissing sound (takes an emrald)
    usage: /scare [player]
  chat:
    description: Get information about the server chat
    usage: /chat